name: Heartbeat

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  heartbeat:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Generate README
        shell: bash
        run: |

          CREATED=$(git log --reverse --format=%ad --date=short | head -1)

          TODAY=$(date +%F)

          DAYS=$(( ( $(date -d "$TODAY" +%s) - $(date -d "$CREATED" +%s) ) / 86400 ))

          FACT=$(shuf -n 1 facts.txt)

          cat > README.md <<EOF
          # 🤖 GitHub Heartbeat

          ![Status](https://img.shields.io/badge/Status-Online-brightgreen)
          ![Updates](https://img.shields.io/badge/Updates-Every%206%20Hours-blue)

          ---

          | Metric | Value |
          |--------|-------|
          | 🕒 Last Update | $(date -u +"%Y-%m-%d %H:%M UTC") |
          | 🌍 Current UTC Time | $(date -u +"%H:%M:%S") |
          | 📅 Days Since Repository Created | $DAYS |
          | 🔢 Total Workflow Runs | ${{ github.run_number }} |

          ---

          ## 💡 Programming Fact

          > $FACT

          ---

          Repository updates automatically every **6 hours** using **GitHub Actions**.
          EOF

      - name: Commit and Push
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add README.md

          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi

          git commit -m "Heartbeat #${{ github.run_number }}"

          git pull --rebase origin main

          git push